- hosts: all
  tasks:
  #- name: copy spring boot file
    #copy:
    #  src: target/SpringBoot-0.0.1-SNAPSHOT.war
      #dest: /opt/tomcat/apache-tomcat-8.5.34/webapps/SpringBoot-0.0.1-SNAPSHOT.war
  get_url:
        force: yes
        url: "http://192.168.33.11:8081/artifactory/Test/SpringBoot-0.0.1-SNAPSHOT.war"
        dest: "/opt/tomcat/apache-tomcat-8.5.34/webapps/SpringBoot-0.0.1-SNAPSHOT.war"
  stat: 
        path: "/opt/tomcat/apache-tomcat-8.5.34/webapps/SpringBoot-0.0.1-SNAPSHOT.war"
